const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const {createServer}=await import('../server/server.mjs');const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1080}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const url=`http://127.0.0.1:${server.address().port}/`;fs.mkdirSync('outputs',{recursive:true});
await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.locator('#start').click();
const {items}=await import('../web/data/items.js');
for(let i=0;i<8;i++){const n=await page.locator('#object-name').textContent();const item=items.find(x=>x.en===n);assert.ok(item);await page.locator(`[data-bin="${item.category}"]`).click();assert.equal(await page.locator('#score').textContent(),String((i+1)*10));await page.locator('#next').click();}
assert.match(await page.locator('#object-name').textContent(),/finished/);assert.equal(await page.locator('#best').textContent(),'80');await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#best').textContent(),'80');
await page.locator('[data-tab="search"]').click();await page.locator('#query').fill('banana');assert.match(await page.locator('#results').textContent(),/Food waste/);await page.locator('#query').fill('<script>bad</script>');assert.match(await page.locator('#results').textContent(),/No match/);await page.locator('#query').fill('纸杯');assert.match(await page.locator('#results').textContent(),/Residual/);
await page.locator('[data-tab="photo"]').click();await page.locator('#walkthrough').click();await page.locator('[data-label="纸杯"]').click();assert.match(await page.locator('#photo-result').textContent(),/Residual/);
await page.locator('#upload').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jfCgAAAAASUVORK5CYII=','base64')});await page.locator('#manual-name').fill('banana');await page.locator('#manual-search').click();assert.match(await page.locator('#photo-result').textContent(),/Food waste/);assert.equal(await page.locator('#live-recognize').isVisible(),false);
await page.locator('[data-tab="story"]').click();await page.evaluate(async()=>{for(const im of document.querySelectorAll('#gallery img'))im.loading='eager';await Promise.all([...document.querySelectorAll('#gallery img')].map(im=>im.decode()));});await page.locator('[data-image="original-game"]').click();assert.equal(await page.locator('#gallery-dialog').evaluate(d=>d.open),true);await page.keyboard.press('Escape');
await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');await page.locator('[data-tab="search"]').click();await page.locator('#query').fill('banana');assert.match(await page.locator('#results').textContent(),/湿垃圾/);await page.locator('#language').click();
await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#library-count').textContent.includes('entries'));await page.locator('#query').fill('bottle');assert.match(await page.locator('#results').textContent(),/Recyclables/);await context.setOffline(false);
// Fresh navigation ensures captures do not retain focus, file uploads or scroll state.
await page.goto(url,{waitUntil:'networkidle'});await page.locator('#start').click();await page.evaluate(()=>document.activeElement.blur());await page.screenshot({path:'outputs/app-desktop.png',fullPage:true});await page.screenshot({path:'outputs/app-desktop-viewport.png'});
await page.locator('[data-tab="photo"]').click();await page.screenshot({path:'outputs/process-1.png',fullPage:true});await page.locator('#walkthrough').click();await page.locator('[data-label="纸杯"]').waitFor();await page.screenshot({path:'outputs/process-2.png',fullPage:true});await page.locator('[data-label="纸杯"]').click();await page.screenshot({path:'outputs/process-3.png',fullPage:true});
await page.setViewportSize({width:390,height:844});for(const tab of ['play','search','photo','story']){await page.locator(`[data-tab="${tab}"]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`outputs/mobile-${tab}.png`,fullPage:true});}await page.locator('[data-tab="play"]').click();await page.locator('#reset').click();await page.locator('[data-bin="1"]').click();assert.equal(await page.locator('#next').isVisible(),true);assert.deepEqual(errors,[]);console.log('Browser checks passed: full game, bilingual search, photo/manual flow, gallery, persistence, offline mode and four mobile sections.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
