import {categories,library,items,search,scoreAnswer,shuffledRound} from './core.js';
const $=id=>document.getElementById(id);let lang='en',deck=[],index=0,score=0,answered=false,filter=0,limit=24,sample='cup',photoData=null,photoURL=null,live=false,walkTimer=null,photoGeneration=0;
const t=(en,zh)=>lang==='en'?en:zh;const cat=id=>categories.find(c=>c.id===id);const name=x=>x[lang];
function storageGet(k){try{return localStorage.getItem(k)||'0';}catch{return '0';}}function storageSet(k,v){try{localStorage.setItem(k,v);}catch{}}
let best=Math.max(0,Number(storageGet('little-sorters-best'))||0);
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function svgBin(c){return `<svg viewBox="0 0 80 105" aria-hidden="true"><rect x="11" y="15" width="58" height="8" rx="3" fill="${c.color}"/><rect x="31" y="9" width="18" height="7" rx="3" fill="${c.color}"/><path d="M15 26H65L61 94Q40 102 19 94Z" fill="${c.color}"/><path d="M22 30L25 91" stroke="#fff" opacity=".2" stroke-width="3"/><text x="40" y="67" text-anchor="middle" font-size="28" font-family="Arial" fill="white">${c.icon}</text></svg>`;}
function drawBins(){ $('bins').innerHTML=categories.slice(0,4).map(c=>`<button class="bin" data-bin="${c.id}" aria-label="${escape(name(c))}" ${!deck.length||answered||index>=deck.length?'disabled':''}>${svgBin(c)}<span>${escape(name(c))}</span></button>`).join('');document.querySelectorAll('[data-bin]').forEach(b=>{b.onclick=()=>answer(Number(b.dataset.bin));b.ondragover=e=>{if(!b.disabled){e.preventDefault();b.classList.add('drag-over');}};b.ondragleave=()=>b.classList.remove('drag-over');b.ondrop=e=>{e.preventDefault();b.classList.remove('drag-over');if(e.dataTransfer.getData('text/plain')==='sort-object')answer(Number(b.dataset.bin));};});}
function drawGame(){ $('score').textContent=score;$('best').textContent=best;$('round').textContent=deck.length?`${Math.min(index+1,8)} / 8`:'— / 8';$('start').hidden=deck.length>0;$('next').hidden=!answered||index>=deck.length;$('object-card').draggable=deck.length>0&&!answered&&index<deck.length;
 if(!deck.length){$('object-emoji').textContent='🌱';$('object-name').textContent=t('Ready, little sorter?','准备好了吗？');$('object-hint').textContent=t('Eight everyday objects. Four possible homes.','八个日常物品，四个可能的家。');$('feedback').textContent='';}
 else if(index>=deck.length){$('object-emoji').textContent='🌟';$('object-name').textContent=t('You finished the challenge!','你完成了挑战！');$('object-hint').textContent=t(`Final score: ${score}. Every try is a chance to learn.`,`最终得分：${score}。每次尝试都是学习的机会。`);$('feedback').textContent='';}
 else{const item=deck[index];$('object-emoji').textContent=item.emoji;$('object-name').textContent=name(item);$('object-hint').textContent=t('Drag me, or choose a bin below.','拖动我，或点击下方垃圾桶。');if(answered)renderFeedback();else $('feedback').textContent='';}drawBins();}
let lastCorrect=false;
function renderFeedback(){const x=deck[index];$('feedback').innerHTML=`<b>${lastCorrect?t('Nice sorting! +10','分类正确！+10'):t('Let’s learn together. −10','一起学习吧。−10')}</b><p>${escape(name(x))} → ${escape(name(cat(x.category)))}</p><p>${escape(lang==='en'?x.tipEn:x.tipZh)}</p>`;}
function answer(id){if(!deck.length||answered||index>=deck.length)return;const result=scoreAnswer(score,deck[index],id);score=result.score;lastCorrect=result.correct;answered=true;best=Math.max(best,score);storageSet('little-sorters-best',best);drawGame();$('next').focus({preventScroll:true});}
function begin(){deck=shuffledRound();index=0;score=0;answered=false;drawGame();}
$('start').onclick=begin;$('reset').onclick=begin;$('next').onclick=()=>{index++;answered=false;drawGame();};$('object-card').ondragstart=e=>{e.dataTransfer.setData('text/plain','sort-object');e.dataTransfer.effectAllowed='move';};
function renderSearch(){const found=search($('query').value,filter);$('library-count').textContent=t(`${library.length.toLocaleString()} archived entries`,`${library.length.toLocaleString()} 条原始记录`);$('filters').innerHTML=[{id:0,en:'All categories',zh:'全部分类'},...categories].map(c=>`<button data-filter="${c.id}" aria-pressed="${filter===c.id}">${escape(name(c))}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=Number(b.dataset.filter);limit=24;renderSearch();});$('result-count').textContent=t(`${found.length} matches · showing ${Math.min(limit,found.length)}`,`${found.length} 条结果 · 显示 ${Math.min(limit,found.length)} 条`);$('results').innerHTML=found.length?found.slice(0,limit).map(x=>{const c=cat(x.category),cur=items.find(i=>i.zh===x.name&&i.category===x.category);return `<article class="result"><h3>${escape(cur&&lang==='en'?cur.en:x.name)}</h3><small>${escape(x.name)}${cur&&lang==='zh'?' · '+escape(cur.en):''}</small><span class="category-label" style="--cat:${c.color||'#245448'}">${escape(name(c))}</span>${cur?`<p>${escape(lang==='en'?cur.tipEn:cur.tipZh)}</p>`:''}</article>`;}).join(''):`<p>${t('No match. Try a Chinese name or another spelling.','没有匹配结果，请尝试其他名称。')}</p>`;$('more').hidden=found.length<=limit;}
$('query').oninput=()=>{limit=24;renderSearch();};$('more').onclick=()=>{limit+=24;renderSearch();};
function photoClear(){clearTimeout(walkTimer);photoGeneration++;$('candidates').textContent='';$('photo-result').textContent='';document.querySelectorAll('[data-step]').forEach(x=>x.classList.toggle('active',x.dataset.step==='0'));}
function samplePhoto(id){sample=id;photoData=null;photoClear();$('upload').value='';$('photo-image').src=`assets/recognition-${id}.jpg`;$('photo-image').alt=t('Original recognition screenshot','原识别测试截图');$('photo-badge').textContent=t('Original final-report screenshot','原结题报告截图');$('photo-note').textContent=t('Recorded-example walkthrough. The labels below are selected from the report; no AI is running and no confidence scores are invented.','归档示例演示。下方名称选自报告，并非实时 AI 识别，也不生成置信度。');$('walkthrough').hidden=false;$('live-recognize').hidden=true;}
function candidates(labels,mode){document.querySelectorAll('[data-step]').forEach(x=>x.classList.toggle('active',x.dataset.step==='1'));$('candidates').innerHTML=labels.map(x=>`<button data-label="${escape(x)}">${escape(x)}</button>`).join('');document.querySelectorAll('[data-label]').forEach(b=>b.onclick=()=>showClassification(b.dataset.label,mode));}
function showClassification(label,mode){const found=search(label);document.querySelectorAll('[data-step]').forEach(x=>x.classList.toggle('active',x.dataset.step==='2'));const exact=found.filter(x=>x.name===label);const results=(exact.length?exact:found).slice(0,4);$('photo-result').innerHTML=`<b>${escape(label)}</b><p>${escape(mode)}</p>`+(results.length?results.map(x=>`<p>${escape(x.name)} → <strong>${escape(name(cat(x.category)))}</strong></p>`).join(''):`<p>${t('No dictionary match. Try a more specific object name.','分类库中没有匹配项，请尝试更具体的物品名。')}</p>`);}
$('walkthrough').onclick=()=>{photoClear();const generation=photoGeneration;walkTimer=setTimeout(()=>{if(generation!==photoGeneration)return;const labels=sample==='cup'?['纸杯','杯子']:['餐巾纸','纸巾'];candidates(labels,t('Recorded example → local dictionary lookup','归档示例 → 本地分类检索'));},400);};document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>samplePhoto(b.dataset.sample));
$('upload').onchange=async()=>{const f=$('upload').files[0];if(!f)return;photoClear();const generation=photoGeneration;if(!['image/jpeg','image/png'].includes(f.type)||f.size>4*1024*1024){$('photo-note').textContent=t('Choose a JPEG or PNG under 4 MB.','请选择小于 4 MB 的 JPEG 或 PNG。');return;}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(f);$('photo-image').src=photoURL;$('photo-image').alt=t('Your local photo preview','你的本地照片预览');$('photo-badge').textContent=t('Your photo · local preview','你的照片 · 本地预览');$('photo-note').textContent=t('Type the object name below. This preview has not been analysed by AI.','在下方输入物品名称，此预览未经过 AI 识别。');$('walkthrough').hidden=true;$('live-recognize').hidden=!live;const reader=new FileReader();reader.onload=()=>{if(generation===photoGeneration)photoData=String(reader.result).split(',')[1];};reader.readAsDataURL(f);};
$('manual-search').onclick=()=>{const q=$('manual-name').value.trim();if(q)showClassification(q,t('Manually entered label → local dictionary','手动输入名称 → 本地分类检索'));};$('manual-name').onkeydown=e=>{if(e.key==='Enter')$('manual-search').click();};
$('live-recognize').onclick=async()=>{if(!live||!photoData)return;const generation=photoGeneration;$('live-recognize').disabled=true;$('photo-note').textContent=t('Sending to Baidu for recognition…','正在发送给百度识别…');try{const res=await fetch('./api/recognize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:photoData}),signal:AbortSignal.timeout(35000)});const data=await res.json();if(!res.ok)throw Error(data.error||'Recognition failed');if(generation!==photoGeneration)return;candidates(data.labels,t('Live Baidu label → local dictionary','实时百度识别 → 本地分类检索'));$('photo-note').textContent=t('Select the object you meant to classify.','请选择想分类的物品。');}catch(e){if(generation===photoGeneration)$('photo-note').textContent=t('Recognition unavailable. You can still type the object name.','识别不可用，仍可手动输入名称。');}finally{$('live-recognize').disabled=false;}};
const gallery=[['requirements','Requirement analysis','需求分析'],['original-game','Original game','原游戏界面'],['original-correct','Correct-answer feedback','答对反馈'],['original-wrong','Wrong-answer feedback','答错反馈'],['original-categories','Four categories','四个分类'],['original-library','Category library','分类库'],['original-search','Keyword search','关键词搜索'],['recognition-cup','Paper cup recognition test','纸杯识别测试'],['cup-results','Paper cup lookup','纸杯分类检索'],['recognition-tissue','Tissue recognition test','纸巾识别测试'],['yellow-tissue','Colour-related recognition error','颜色导致的识别错误'],['background-error','Background distraction','背景干扰']];
function renderGallery(){$('gallery').innerHTML=gallery.map(([f,en,zh])=>`<button data-image="${f}" data-caption="${escape(t(en,zh))}"><img loading="lazy" src="assets/${f}.jpg" alt="${escape(t(en,zh))}"><span>${escape(t(en,zh))}</span></button>`).join('');document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{$('enlarged').src=`assets/${b.dataset.image}.jpg`;$('enlarged').alt=b.dataset.caption;$('caption').textContent=b.dataset.caption;$('gallery-dialog').showModal();});}
$('close-gallery').onclick=()=>$('gallery-dialog').close();
function translate(){document.documentElement.lang=lang==='en'?'en':'zh-CN';document.querySelectorAll('[data-en]').forEach(x=>x.innerHTML=x.dataset[lang]);$('language').textContent=lang==='en'?'中文':'English';$('recognition-mode').textContent=live?t('Local server · live AI available','本地服务器 · 可用实时 AI'):t('Recorded-example demo','归档示例演示');drawGame();renderSearch();renderGallery();samplePhoto(sample);}
$('language').onclick=()=>{lang=lang==='en'?'zh':'en';translate();};
function route(){const id=location.hash.slice(1);const active=['play','search','photo','story'].includes(id)?id:'play';document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==active);document.querySelectorAll('[data-tab]').forEach(x=>{if(x.dataset.tab===active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});}
window.addEventListener('hashchange',route);translate();route();
// Public GitHub Pages makes no API request. Only the optional localhost server is probed.
if(['localhost','127.0.0.1','[::1]'].includes(location.hostname))fetch('./api/status').then(r=>r.json()).then(d=>{live=!!d.live;$('recognition-mode').textContent=live?t('Local server · live AI available','本地服务器 · 可用实时 AI'):t('Recorded-example demo','归档示例演示');}).catch(()=>{});
let installEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').hidden=false;});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('install').hidden=true;}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
